[package]
name = "match-lowering"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[profile.bench]
codegen-units = 1
lto = true

[[bench]]
name = "my_benchmark"
harness = false
